//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica
    {
        public int ID_anagrafica { get; set; }
        public System.DateTime data_nascita { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string sesso { get; set; }
        public string codice_fiscale { get; set; }
        public string p_iva { get; set; }
        public string indirizzo { get; set; }
        public string cap { get; set; }
        public string citta { get; set; }
        public string provincia { get; set; }
        public string carta_identita { get; set; }
        public System.Guid utente_id { get; set; }
        public string tel { get; set; }
        public string cell { get; set; }
        public string fax { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
