//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int ID_foto { get; set; }
        public string path { get; set; }
        public Nullable<int> ordine { get; set; }
        public int gallery_id { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
