//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_tipo
    {
        public int ID_gallery_tipo { get; set; }
        public int tipi_gallery_id { get; set; }
        public int profilo_id { get; set; }
    }
}
