//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.Eventis = new HashSet<Eventi>();
            this.Fotoes = new HashSet<Foto>();
            this.Profiloes = new HashSet<Profilo>();
        }
    
        public int ID_gallery { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Eventi> Eventis { get; set; }
        public virtual ICollection<Foto> Fotoes { get; set; }
        public virtual ICollection<Profilo> Profiloes { get; set; }
    }
}
