//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livello_Utenti
    {
        public Livello_Utenti()
        {
            this.Utentis = new HashSet<Utenti>();
        }
    
        public int ID_livello { get; set; }
        public int livello { get; set; }
        public string descrizione { get; set; }
    
        public virtual ICollection<Utenti> Utentis { get; set; }
    }
}
