//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profilo
    {
        public Profilo()
        {
            this.Eventis = new HashSet<Eventi>();
            this.Telefonoes = new HashSet<Telefono>();
        }
    
        public System.Guid ID_profilo { get; set; }
        public string nome { get; set; }
        public string logo { get; set; }
        public string indirizzo { get; set; }
        public string cap { get; set; }
        public string citta { get; set; }
        public decimal latitudine { get; set; }
        public decimal longitudine { get; set; }
        public string desc_breve { get; set; }
        public string desc_long { get; set; }
        public System.Guid utente_id { get; set; }
        public Nullable<int> gallery_id { get; set; }
        public int categoria_id { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Eventi> Eventis { get; set; }
        public virtual Gallery Gallery { get; set; }
        public virtual Utenti Utenti { get; set; }
        public virtual ICollection<Telefono> Telefonoes { get; set; }
    }
}
