//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti
    {
        public Utenti()
        {
            this.Anagraficas = new HashSet<Anagrafica>();
            this.Profiloes = new HashSet<Profilo>();
        }
    
        public int ID_utente { get; set; }
        public string usename { get; set; }
        public string password { get; set; }
        public int livello_id { get; set; }
    
        public virtual ICollection<Anagrafica> Anagraficas { get; set; }
        public virtual Livello_Utenti Livello_Utenti { get; set; }
        public virtual ICollection<Profilo> Profiloes { get; set; }
    }
}
